#!/usr/bin/env node
/* =========================================================================
   build-words.mjs — builds the shared word pool in assets/data/words/.

   Sources (downloaded once into tools/.cache/words/):
     • ENABLE (public domain)            what counts as a word; plurals + conjugations included
     • Norvig count_1w.txt               Google web 1T counts: how common on the web
     • hermitdave FrequencyWords en_full OpenSubtitles counts: how common in speech
   A word joins the pool when it is in ENABLE, is 3–12 lowercase letters, and clears a
   floor in BOTH corpora. Obscure entries that only look common because they are also
   names are dropped when the system dictionary lists them capitalized only (base words
   only, so plurals like "kids" are safe). A short blocklist removes words unsuitable
   for students. Each length file also carries `extra`: other ENABLE words that are
   anagrams of pool words, so a rarer anagram a student types is still accepted.

   Usage: node tools/build-words.mjs            (needs network the first time)
   ========================================================================= */
import { mkdir, readFile, writeFile, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve, join } from "node:path";

const ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)));
const CACHE = join(ROOT, "tools", ".cache", "words");
const OUT = join(ROOT, "assets", "data", "words");
const PROPER_FILE = join(ROOT, "tools", "words", "proper-nouns.txt");
const BLOCK_FILE = join(ROOT, "tools", "words", "blocklist.txt");

const SOURCES = {
  enable: "https://raw.githubusercontent.com/dolph/dictionary/master/enable1.txt",
  web: "https://norvig.com/ngrams/count_1w.txt",
  subs: "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/en/en_full.txt",
};
const MIN_LENGTH = 3, MAX_LENGTH = 12;
/* frequency floors per word length: short strings pick up noise (abbreviations,
   OCR junk) in both corpora, so 3- and 4-letter words must clear higher bars */
const FLOORS = (L) => (L === 3 ? { web: 2_000_000, subs: 1_000 } : L === 4 ? { web: 300_000, subs: 150 } : { web: 100_000, subs: 50 });
/* commonness tiers by subtitle count: 1 = everyday speech … 6 = rare */
const TIER_CUTS = [10_000, 3_000, 1_000, 300, 100];

async function fetchCached(name, url) {
  await mkdir(CACHE, { recursive: true });
  const file = join(CACHE, name);
  if (!existsSync(file) || (await stat(file)).size === 0) {
    process.stdout.write(`downloading ${url} … `);
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
    await writeFile(file, Buffer.from(await res.arrayBuffer()));
    console.log("ok");
  }
  return readFile(file, "utf8");
}

const lines = (text) => text.split(/\r?\n/).filter(Boolean);

async function readListFile(path) {
  if (!existsSync(path)) return new Set();
  return new Set(lines(await readFile(path, "utf8")).map((l) => l.trim().toLowerCase()).filter((l) => l && !l.startsWith("#")));
}

/** Blocklist: exact words, plus `root*` entries that block any word containing `root`. */
function makeBlocker(entries) {
  const exact = new Set(), roots = [];
  for (const e of entries) (e.endsWith("*") ? roots.push(e.slice(0, -1)) : exact.add(e));
  return (w) => exact.has(w) || roots.some((r) => w.includes(r));
}

/** Words the system dictionary lists only capitalized: names, places, brands. Cached to a committed file. */
async function properNouns() {
  const sys = "/usr/share/dict/words";
  if (existsSync(sys)) {
    const lower = new Set(), capital = new Set();
    for (const w of lines(await readFile(sys, "utf8"))) {
      if (/^[a-z]+$/.test(w)) lower.add(w);
      else if (/^[A-Z][a-z]+$/.test(w)) capital.add(w.toLowerCase());
    }
    const only = [...capital].filter((w) => !lower.has(w)).sort();
    await mkdir(join(ROOT, "tools", "words"), { recursive: true });
    await writeFile(PROPER_FILE, `# words the system dictionary (web2) lists only capitalized; generated by build-words.mjs\n${only.join("\n")}\n`);
    return new Set(only);
  }
  console.log("no system dictionary here; using the committed proper-nouns.txt");
  return readListFile(PROPER_FILE);
}

/** Is `w` a plural/conjugation/comparative of some other word in `pool`? Such words are never name-filtered. */
function isInflection(w, pool) {
  const stems = [];
  if (w.endsWith("ies")) stems.push(w.slice(0, -3) + "y");
  if (w.endsWith("es")) stems.push(w.slice(0, -2));
  if (w.endsWith("s")) stems.push(w.slice(0, -1));
  if (w.endsWith("ed")) stems.push(w.slice(0, -2), w.slice(0, -1), w.slice(0, -3));
  if (w.endsWith("ing")) stems.push(w.slice(0, -3), w.slice(0, -3) + "e", w.slice(0, -4));
  if (w.endsWith("er")) stems.push(w.slice(0, -2), w.slice(0, -1), w.slice(0, -3));
  if (w.endsWith("est")) stems.push(w.slice(0, -3), w.slice(0, -2), w.slice(0, -4));
  if (w.endsWith("ly")) stems.push(w.slice(0, -2));
  return stems.some((s) => s.length >= 2 && pool.has(s));
}

const tierOf = (subsCount) => {
  const i = TIER_CUTS.findIndex((cut) => subsCount >= cut);
  return i < 0 ? TIER_CUTS.length + 1 : i + 1;
};
const signature = (w) => [...w].sort().join("");

async function main() {
  const [enableText, webText, subsText] = await Promise.all([
    fetchCached("enable1.txt", SOURCES.enable),
    fetchCached("count_1w.txt", SOURCES.web),
    fetchCached("en_full.txt", SOURCES.subs),
  ]);
  const enable = new Set(lines(enableText).map((w) => w.trim()).filter((w) => /^[a-z]+$/.test(w)));
  const web = new Map();
  for (const l of lines(webText)) { const [w, c] = l.split("\t"); if (w && c) web.set(w, Number(c)); }
  const subs = new Map();
  for (const l of lines(subsText)) { const [w, c] = l.split(" "); if (w && c) subs.set(w, Number(c)); }
  const proper = await properNouns();
  const blocked = makeBlocker(await readListFile(BLOCK_FILE));

  // 1) frequency gate
  const gated = new Set();
  for (const w of enable) {
    if (w.length < MIN_LENGTH || w.length > MAX_LENGTH) continue;
    const floor = FLOORS(w.length);
    if ((web.get(w) || 0) >= floor.web && (subs.get(w) || 0) >= floor.subs) gated.add(w);
  }
  // 2) name filter (base words only) and blocklist
  const pool = new Set();
  const dropped = { names: [], blocked: [] };
  for (const w of gated) {
    if (blocked(w)) { dropped.blocked.push(w); continue; }
    if (proper.has(w) && !isInflection(w, gated)) { dropped.names.push(w); continue; }
    pool.add(w);
  }

  // 3) per-length files
  await mkdir(OUT, { recursive: true });
  const manifest = { builtAt: new Date().toISOString().slice(0, 10), minLength: MIN_LENGTH, maxLength: MAX_LENGTH, total: 0,
    thresholds: { floors: { 3: FLOORS(3), 4: FLOORS(4), other: FLOORS(5) }, tierCuts: TIER_CUTS },
    sources: {
      enable: { url: SOURCES.enable, license: "public domain", role: "validity (plurals and conjugations included)" },
      web: { url: SOURCES.web, note: "Peter Norvig's unigram counts from the Google Web Trillion Word Corpus", role: "web frequency" },
      subs: { url: SOURCES.subs, license: "CC-BY-SA 4.0 (hermitdave/FrequencyWords, OpenSubtitles 2018)", role: "speech frequency and tiers" },
    },
    lengths: {} };
  let totalBytes = 0;
  for (let L = MIN_LENGTH; L <= MAX_LENGTH; L++) {
    const words = [...pool].filter((w) => w.length === L)
      .sort((a, b) => (subs.get(b) - subs.get(a)) || (web.get(b) - web.get(a)) || a.localeCompare(b));
    const tiers = words.map((w) => tierOf(subs.get(w))).join("");
    const sigs = new Set(words.map(signature));
    const extra = [...enable].filter((w) => w.length === L && !pool.has(w) && !blocked(w) && sigs.has(signature(w))).sort();
    const data = { length: L, words: words.join(" "), tiers, extra: extra.join(" ") };
    const json = JSON.stringify(data);
    await writeFile(join(OUT, `${L}.json`), json);
    totalBytes += json.length;
    const groups = new Map(); for (const w of words) groups.set(signature(w), (groups.get(signature(w)) || 0) + 1);
    manifest.lengths[L] = { words: words.length, extra: extra.length, multiAnagramSets: [...groups.values()].filter((n) => n > 1).length, bytes: json.length };
    manifest.total += words.length;
    console.log(`len ${String(L).padStart(2)}: ${String(words.length).padStart(5)} words · ${String(extra.length).padStart(5)} extra · ${String(manifest.lengths[L].multiAnagramSets).padStart(4)} multi-anagram sets · ${(json.length / 1024).toFixed(0)} KB`);
  }
  await writeFile(join(OUT, "index.json"), JSON.stringify(manifest, null, 2) + "\n");
  console.log(`total ${manifest.total} words · ${(totalBytes / 1024).toFixed(0)} KB · dropped ${dropped.names.length} name-like, ${dropped.blocked.length} blocked`);
  console.log("name-like sample:", dropped.names.sort(() => Math.random() - 0.5).slice(0, 40).join(" "));
}

main().catch((err) => { console.error(err); process.exit(1); });
